<p><a name="sections"></a></p>


# Sections

- <a href="#numpy">Numpy Overview</a><br>
- <a href="#array">Ndarray</a><br>
    - <a href="#dtype">Data Type</a><br>
    - <a href="#create">Creating Data Array</a><br>
- <a href="#slice">Subscripting and Slicing</a><br>
    - <a href="#shape">Shape</a><br>
    - <a href="#operations">Operations</a><br>

<p><a name="numpy"></a></p>
## NumPy Overview

NumPy is the fundamental package for scientific computing with Python. 

- Primitive data types are often collected and arranged in certain ways to facilitate analysis. A common example are **vectors** and **matrices** in linear algebra. Numpy provide easy tools to achieve it. 
- Numpy provides many functions and modules for scientific uses, such as linear algebra operations, random number generation, Fourier transform, etc.

For full documentation, go to:  http://docs.scipy.org/doc/.

As a module, you need to import it to make the functions it has accessible. You can do it by run the following code:

In [1]:
import numpy as np

Whenever you need to call a function from Numpy, say `arange()`, you could run:
```
np.arange( arguments )
```

<p><a name="array"></a></p>
## Ndarray

<p><a name="dtype"></a></p>
### Data Type
NumPy provides an N-dimensional array type, the `ndarray`. It can be described as a collection of elements of the same data type. We will discuss more about the creation of ndarray, but for the illustrating purpose, let’s construct a simple example with the function `array()`.

In [5]:
# the most fundamental data structure in Python is List
# the most fundamental data structure in NumPy is Ndarray

my_ary=np.array([1,2,3])
my_ary

array([1, 2, 3])

We see that `array()` takes a list as an argument. Then `my_ary` is a ndarray with three elements ordered exactly the same as the list inputted.

In [3]:
print type(my_ary)
print my_ary

<type 'numpy.ndarray'>
[1 2 3]


As you might suspect, each element in `my_ary` can be accessed by integer index. Details of indexing will be provided later.

In [4]:
print my_ary[0]  # In Python, first index is 0
print my_ary[1]

1
2


The type ndarray is flexible because it supports great variety of primitive data types:
- http://docs.scipy.org/doc/numpy/user/basics.types.html

subject to the **homogeneity condition**, which means every element in ndarray have the same type. The type of the elements can be accessed as an attribute of an ndarray.

In [6]:
my_ary.dtype   #dtype is a feature of ndarray not a method

dtype('int32')

When the elements are of string types, it print the dtype automatically. The letter `‘S’ ` stands for string and the number followed represents the largest number of letters among all the elements. 

In [5]:
np.array(['a', 'ab'])

array(['a', 'ab'], 
      dtype='|S2')

If the list inputted to the function `array()` is of mixed types, Numpy (upcast) cast all elements to a common (superclass) class:

In [7]:
print np.array([1.0, 2, 3])
print np.array(['a', 2, 3])

[1. 2. 3.]
['a' '2' '3']


<p><a name="create"></a></p>
### Creating Data Array

We have already seen a way to generate ndarray by plugging a list into the function `array()`. This method can be actually generalized to create multidimensional array by plugging nested list instead of simple list into the `array()` function.

In [7]:
simple_lst = [1,2]
nested_lst = [[1,2], [3,4], [5,6]]
multi_ary = np.array(nested_lst)
multi_ary

# numPy is meant to work with rectangular arrays 

array([[1, 2],
       [3, 4],
       [5, 6]])

So far we have been creating arrays mainly by specifying every element. When creating larger arrays this is not practical. Numpy provides functions which create functions by certain **rules**. We discuss some of them below.

- The simplest way to create a Numpy array is by the function `arange()`.

In [8]:
range(10)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [14]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Plugging float into `arange()` result in array upto the greatest number smaller than the float.

In [10]:
np.arange(9.5)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

We don’t have to always start from 0. The first argument below indicates the array starts from 2 and the second argument indicates it stops at 9 (10-1).

In [12]:
np.arange(2, 10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
range(2,10)

[2, 3, 4, 5, 6, 7, 8, 9]

And step between terms doesn’t need to be 1. Below we specify the step to be 3 as the third argument, therefore 2 + 3 = 5, then 5 + 3 = 8. Since the next one 8 + 3 = 11, which is greater than the upper bound 9, so it stops at 8.

In [13]:
np.arange(2,10,3)  # the third argument determines the increment 

array([2, 5, 8])

A very similar method is linspace(). It takes the start (first argument), the end (second argument) and  the desired length (last argument).

In [16]:
np.linspace(0,10, 51)  # inclusive of 10 
# 51 steps, 50 data points
# n+1 steps, n data points


array([  0. ,   0.2,   0.4,   0.6,   0.8,   1. ,   1.2,   1.4,   1.6,
         1.8,   2. ,   2.2,   2.4,   2.6,   2.8,   3. ,   3.2,   3.4,
         3.6,   3.8,   4. ,   4.2,   4.4,   4.6,   4.8,   5. ,   5.2,
         5.4,   5.6,   5.8,   6. ,   6.2,   6.4,   6.6,   6.8,   7. ,
         7.2,   7.4,   7.6,   7.8,   8. ,   8.2,   8.4,   8.6,   8.8,
         9. ,   9.2,   9.4,   9.6,   9.8,  10. ])

Without the last argument, the length defaults 50.

**Regular Creating**

We might want to construct a constant array. The function `ones()` returns an array with as many 1 as the number plugged in.

In [17]:
np.ones(3)

array([ 1.,  1.,  1.])

In [18]:
np.ones([3,4])

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [15]:
np.ones([3,4])*10   # you can't do that with a Python list (you need a map function)

array([[10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.]])

We can construct all the constant array by multiply the desired constant to a array produced as above. The details of array operation will be discussed, but multiplying a number to an array results in every entry in the array multiplied by the constant.

In [26]:
import math
math.pi *np.ones(5)

array([ 3.14159265,  3.14159265,  3.14159265,  3.14159265,  3.14159265])

We have seen from above that we can easily generate a zero array by times 0 to a array generated by the function `ones()`. However, Numpy also provides a function `zeros()`, which works in the same way as the function `ones()`:

In [27]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [30]:
a=np.array([1.,2.,3.])
b=np.array([3.,4.,5.])
print a*b  # element-wise multiplication
print a+b  # element-wise adding
print a/b  # element-wise division

[  3.   8.  15.]
[ 4.  6.  8.]
[ 0.33333333  0.5         0.6       ]


<p><a name="slice"></a></p>
## Subscripting and Slicing

We often need to access a particular element (subscripting) in our array. We have already seen that ndarray is treated as an ordered sequence, whose entries are indexed by integers. 

In [16]:
x = np.arange(1, 11)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

We may print out an arbitrary entry. For example, the 3rd element in x:

In [32]:
x[2]  # Python index from 0

3

We may then plug it into a function:

In [33]:
3**(x[2])

27

In [34]:
3**x   # we don't have to do a mapping

array([    3,     9,    27,    81,   243,   729,  2187,  6561, 19683, 59049])

We may update an element with indexes:

In [35]:
x[2] = 100
x

array([  1,   2, 100,   4,   5,   6,   7,   8,   9,  10])

Negative indexes select the element by the opposite order.

In [36]:
print x[-1]; print x[-2]; print x[-10]

10
9
1


**Exercise 1**

Initialize x again with:
```
x = np.arange(1, 11)
```
Run `x[2]=3.0`. Which entry of the array x will be updated?
Run `x[2]=3.1`. Which entry of the array x will be updated?
Run `x.astype(float)` to change the type to float, then update the third element to 3.1.

In [17]:
x = np.arange(1, 11)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
#### Your code here
x[2]=3.1
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
x.astype(float)
x[2]=3.1
x

# astype() is not a mutating function. 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
x = x.astype(float)
x[2]=3.1
x   # works!!!

array([ 1. ,  2. ,  3.1,  4. ,  5. ,  6. ,  7. ,  8. ,  9. , 10. ])

We often need to subscript in a higher dimensional array. We start by constructing one:

In [20]:
high_x = np.array([[1,2,3],[4,5,6]])
high_x

array([[1, 2, 3],
       [4, 5, 6]])

As we mentioned before, 2-dimensional ndarray can be thought as a nested list. Therefore, to access the number 2, it is the element 1 in the list 0:

In [49]:
high_x[0][1]

2

In [50]:
high_x[0,1]

2

In this way, we may slice a particular row by selecting an inner list:

In [51]:
high_x[1]

array([4, 5, 6])

A 2-dimensional array can be also taken for a matrix.

\begin{pmatrix}
1 &2  &3 \\ 
4 &5  &6 
\end{pmatrix}

Therefore as matrices, a 2-dimensional array can be indexed a pair of integers -- row indexes and columns indexes. Conventionally, the first index is for row, the second for column.


In [52]:
print high_x[0,0], high_x[0,1], high_x[0,2]
print high_x[1,0], high_x[1,1], high_x[1,2]

1 2 3
4 5 6


In [53]:
# these two are equivalent 
print high_x[0,1]
print high_x[0][1]

2
2


We may then slice part of the second row by specifying the row index and the range of the columns.

In [54]:
high_x[1,0:2]

array([4, 5])

When specifying index to be from the first entry, we can leave it blank.

In [55]:
high_x[1,:2]

array([4, 5])

<p><a name="shape"></a></p>
### Shape

Again as a matrix, the shape of an array can be denoted by the number of rows and columns it has. And again, first rows and then columns. For example, consider  the following is a 2 by 3 matrix.

\begin{pmatrix}
1 &2  &3 \\ 
4 &5  &6 
\end{pmatrix}

For an array, the shape (or dimension in more matrix convention) can be seen by calling the `.shape` attribute.

In [56]:
high_x.shape  # it's not a method, it's an attribute, that's why it doesn't have ()

(2L, 3L)

In [57]:
cols = high_x.shape[1]
cols

3L

Now we understand the notation of the shape. We may discuss the regular creation of 2-dimensional arrays. We start with generating a constant matrix by the functions `ones()`.

In [58]:
np.ones([2,3])

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

The function `zero()` works in the same way:

In [23]:
np.zeros([3,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

We may also rearrange the shape of a 1-dimensional array to obtain a higher dimensional one. This can be done by a method `reshape()`:

In [60]:
x = np.arange(8)
x.reshape([2,4])

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
# question: how can you produce something like this:(hint: look at reshape documentation):

([[0,2,4,6],
  [1,3,5,7]])


This can also be achieved by assigning the desired value to the attribute `.shape`

In [66]:
x = np.arange(8)
x.shape = (2,4)
x

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

**Exercise 2**

- Create a 4 by 5 five matrix with all the  entries 8.
- Create an array corresponding to the matrix below:
\begin{pmatrix}
9 &8  &7 \\ 
6 &5  &4 
\end{pmatrix}

In [ ]:
#### Your code here
a = np.ones([4,5])*8
a

In [ ]:
np.arange(9,3,-1).reshape(2,3)

<p><a name="operations"></a></p>
### Operations

**Arithmetic Operations**

We often want to do math on an array. Addition of more than one array and scalar multiplication works as we expect: 

In [28]:
x = np.array([1,2])
y = np.array([3,4])
z = np.array([5,6])
x + y + z

array([ 9, 12])

In [74]:
5*x

array([ 5, 10])

Addition is actually an example of **pointwise operations**. Here is another example:

In [75]:
y*z       # Same rule applies to multiplication

array([15, 24])

All the arithmetic operators can work pointwisely

In [76]:
x**y

array([ 1, 16])

In [77]:
y/x 

array([3, 2])

In [78]:
y-x

array([2, 2])

In [79]:
z%y 

array([2, 2])

On the other hand, scalar product is an special case of **broadcasting**:

In [80]:
x+3 

array([4, 5])

All the arithmetic operators can be broadcasted similarly

In [81]:
x**2

array([1, 4])

In [82]:
x/2

array([0, 1])

In [83]:
y-3

array([0, 1])

In [84]:
z%3   

array([2, 0])

**Comparison Operations**

Comparison operators generates Boolean arrays. As arithmetic operators, they also follow the broadcasting rule.

In [29]:
print x
x>1

[1 2]


array([False,  True])

In [86]:
y=x>1
y.dtype

dtype('bool')

All the comparison operators can be broadcasted similarly.

In [87]:
x<1

array([False, False], dtype=bool)

In [88]:
y<=3

array([ True,  True], dtype=bool)

In [ ]:
z>=6

In [ ]:
z==5

Comparison operators can be applied pointwisely to multiple arrays. This is different from **lists**.

In [ ]:
x>y  

All the operators can be broadcasted similarly.

In [ ]:
x < y

In [ ]:
y<=z

In [ ]:
z>=x

In [ ]:
z==x

**Fancy Indexing**

We often need to filter an array according to some condition. This can be done by two steps.

- Generate Boolean array

In [30]:
x==1

array([ True, False])

- Slice the array with the Boolean array

In [ ]:
# x=[1,2]
x[np.array([ True, False])]

The two steps can be actually combined

In [89]:
x[x==1]  # this is called fancy indexing

array([1])

In [90]:
#print the even elements of x:
x[x%2==0]


array([2])

Fancy indexing can be applied to (higher) 2 dimensional arrays. However, slicing with fancy index drop the structure to the 1 dimensional array.

In [91]:
high_x = np.array([[1,2,3],[4,5,6]])
high_x[high_x>=3]

array([3, 4, 5, 6])

However, assignment with fancy indexing doesn’t change the shape.

In [92]:
high_x[high_x>=3]=10
high_x


array([[ 1,  2, 10],
       [10, 10, 10]])

** Exercise 3**

Run the code below to create arrays.

```
ary_1= np.ones([3,2])
ary_2=np.arange(1,7).reshape(3,2)
```
- Sum up the arrays.
- Add 1 to the first column of `ary_1`, and add 2 to the second column of `ary_1`.
- Update `ary_2`: change any number greater than 4 to 2.5. 


In [103]:
ary_1= np.ones([3,2])
ary_2=np.arange(1,7).reshape(3,2)

In [104]:
#### Your code here
print ary_1
print ary_2



[[ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]]
[[1 2]
 [3 4]
 [5 6]]


In [105]:
ary_1 + ary_2

array([[ 2.,  3.],
       [ 4.,  5.],
       [ 6.,  7.]])

In [106]:
sum(sum(ary_1))
#or
ary_1.sum()

6.0

In [107]:
ary_1[:,0] = ary_1[:,0]+1
ary_1[:,1] = ary_1[:,1]+2
ary_1


array([[ 2.,  3.],
       [ 2.,  3.],
       [ 2.,  3.]])

In [108]:
ary_2=ary_2.astype(float)
ary_2[ary_2 > 4] = 2.5
ary_2

array([[ 1. ,  2. ],
       [ 3. ,  4. ],
       [ 2.5,  2.5]])

In [113]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.concatenate((a,b)).reshape([2,4])
c

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [109]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print a
print a.T


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


# Pandas

<p><a name="DS"></a></p>
### Data Structure

- Pandas is a large package defining several new data types, plus a variety of convenient functions for data manipulation, plotting, and web scraping.

- The *DataFrame* structure is inspired by the type of same name in R, a programming language popular among statisticians and data scientists.

- Pandas is particularly strong in the area of handling missing data and, relatedly, handling time series data.

- There are four new data structures in pandas: Series, DataFrame, time series and panel. We will mainly discuss the first three.

These are the new data types introduced by pandas:

- **Series**: 1D labeled homogeneously-typed array.
- **DataFrame**: General 2D labeled, size-mutable tabular structure with potentially heterogeneously-typed columns.
- **Time Series**: Series with index containing datetimes.
- **Panel**: General 3D labeled, also size-mutable array.

We first import the package

In [31]:
import numpy as np
import pandas as pd

<p><a name="series"></a></p>
## Series

A series is a one-dimensional array-like object containing an array of data (of any NumPy data type) and an associated array of data labels, called its index. By default, the index just consists of ordinary array indices, i.e. consecutive integers starting from zero.

In [33]:
obj = pd.Series(['a', 'b', 'c', 'd'])
obj

0    a
1    b
2    c
3    d
dtype: object

Often it will be more desirable to create a series with an index identifying each data point. Here we manually set the index from 1 to 4.

In [34]:
obj2 = pd.Series(['a', 'b', 'c', 'd'], index=[1, 2, 3, 4])
obj2

1    a
2    b
3    c
4    d
dtype: object

The method `values` accesses all the values.

In [35]:
obj.values

array(['a', 'b', 'c', 'd'], dtype=object)

In [118]:
obj.values[1]   # obj.values is simply an array 

'b'

The **Series** object is similar to a **dictionary**, `Series.index` is like `dictionary.keys`, and `Series.values` is like `dictionary.values`. We can convert a dictionary to a Series directly:

In [119]:
dict_ = {1: 'a', 2: 'b', 3: 'c', 4: 'd'}
obj3 = pd.Series(dict_)
obj3

1    a
2    b
3    c
4    d
dtype: object

We can of course convert a Series back to a dictionary.

In [120]:
obj3.to_dict()

{1: 'a', 2: 'b', 3: 'c', 4: 'd'}

<p><a name="DF"></a></p>
## DataFrame

A data frame represents a tabular, spreadsheet-like data structure containing an ordered collection of columns, each of which can be a different value type (integers, strings, floating point numbers, Python objects, etc.), but all must be the same length.

In [36]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9]}
# convert to DataFrame
df = pd.DataFrame(data)
df

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002

A data frame can be created with nested list as well. The two ways are equivalent.

In [37]:
df_2=pd.DataFrame([[1.5, 'Ohio', 2000],
                   [1.7, 'Ohio', 2001],
                   [3.6, 'Ohio', 2002],
                   [2.4, 'Nevada', 2001],
                   [2.9, 'Nevada', 2002]], 
                    columns=['pop','state','year'])
df_2

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002

In [39]:
df_3=pd.DataFrame([[1.5, 'Ohio', 2000],
                   [1.7, 'Ohio', 2001],
                   [3.6, 'Ohio', 2002],
                   [2.4, 'Nevada', 2001],
                   [2.9, 'Nevada', 2002]])
df_3.columns=['pop','state','year']
df_3

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002

A data frame has an attribute **values**, which is of the multidimensional array type.

In [126]:
print df.values
print '-'*55
print df_2.values

[[1.5 'Ohio' 2000L]
 [1.7 'Ohio' 2001L]
 [3.6 'Ohio' 2002L]
 [2.4 'Nevada' 2001L]
 [2.9 'Nevada' 2002L]]
-------------------------------------------------------
[[1.5 'Ohio' 2000L]
 [1.7 'Ohio' 2001L]
 [3.6 'Ohio' 2002L]
 [2.4 'Nevada' 2001L]
 [2.9 'Nevada' 2002L]]


data frame v.s. series is similar to 2D array v.s. 1D array. A data frame has column names.

In [41]:
print df.columns    # column names
# here u'pop' means the string 'pop' is encoded in unicode

print list(df.columns)

Index([u'pop', u'state', u'year'], dtype='object')
['pop', 'state', 'year']


Each column in a DataFrame can be retrieved as a Series. We have two ways to get the column: to retrieve by attribute and to retrieve by dictionary-like notation. They will give the same result.

In [42]:
df.year         # retrieve by attribute

0    2000
1    2001
2    2002
3    2001
4    2002
Name: year, dtype: int64

In [44]:
df[['year']]  # retrieve by dictionary-like notation > the result is another pandas dataframe

year
0  2000
1  2001
2  2002
3  2001
4  2002

In [10]:
df[['pop','state']]

pop   state
0  1.5    Ohio
1  1.7    Ohio
2  3.6    Ohio
3  2.4  Nevada
4  2.9  Nevada

** Exercise 4** 

Create a Pandas DataFrame, 'Employee', whose columns are 'Name', 'Year' and 'Department'. The rows are supposed to be:

- Bob has been working for IT department for a year.
- Sam has been working for Trade department for 3 years.
- Peter has been working for HR department for 8 years.
- Jake has been working for IT department for 2 years.

Now set the index of Employee to be their names using `set_index` function of a data frame. Make sure you update the DataFrame.

In [45]:
#### Your code here

Employees = pd.DataFrame([['Bob',1,'IT'],['Sam',3,'Trade'],['Peter',8,'HR'],['Jake',2,'IT']])
Employees.columns=['Name','Year','Department']
Employees

Name  Year Department
0    Bob     1         IT
1    Sam     3      Trade
2  Peter     8         HR
3   Jake     2         IT

<p><a name="IO"></a></p>
## I/O tools

Pandas has a number of functions for reading tabular data as a data frame object.

In [46]:
!more foo.csv

a,b,c,d,message
1,2,3,4,hello
5,6,7,8,world
9,10,11,12,foo


In [47]:
pd.read_csv('foo.csv')

a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

Parsing can't be done properly with a bad delimiter

In [137]:
# read_csv reads a \t separated file
pd.read_csv('foo.txt')

a\tb\tc\td\tmessage
0   1\t2\t3\t4\thello
1   5\t6\t7\t8\tworld
2  9\t10\t11\t12\tfoo

- We saw the data frame becomes messy with a bad delimiter.

The problem will be fixed by passing sep = '\t' to read_csv.

In [138]:
# read_csv reads a \t separated file
pd.read_csv('foo.txt', sep='\t')

a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In some cases, there is no header in the file. Set `header = None`, the column names will be filled with incremental numbers.

In [139]:
#!cat foo_noheader.csv
!more foo_noheader.csv

1,2,3,4,hello
5,6,7,8,world
9,10,11,12,foo


In [145]:
pd.read_csv('foo_noheader.csv', header = None)

0   1   2   3      4
0  1   2   3   4  hello
1  5   6   7   8  world
2  9  10  11  12    foo

But we can pass the column names (as a list of strings) to the names parameter in `read_csv`.

In [21]:
# Set the names manually
df = pd.read_csv('foo_noheader.csv', 
             names=['a', 'b', 'c', 'd', 'message'])

df

a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

So far we covered only importing a file. With this exercise we first demonstrate how exporting is done.

**Exercise 5** 

- Write the data frame, `Employee`, to a file, Employee.csv. The function `to_csv` should comes in handy.


In [149]:
#### Your code here

Employees.to_csv('Employees.csv')

# Data Manipulation in Pandas

Like numpy, pandas defines many broadcast operations, as well as numerous methods of manipulating data.
<p><a name="concat"></a></p>
### concat
Pandas DataFrames can be expanded in both directions. Let’s create two data frames first.

In [48]:
df1 = pd.DataFrame(np.arange(9).reshape((3, 3)), 
                   columns=['a', 'b', 'c'],
                   index=['one', 'two', 'three'])
df2 = pd.DataFrame(np.arange(6).reshape((3, 2)), 
                   columns=['d','e'],
                   index=['one', 'two', 'three'])

In [49]:
df1

a  b  c
one    0  1  2
two    3  4  5
three  6  7  8

In [50]:
df2

d  e
one    0  1
two    2  3
three  4  5

Since the two data frames have the same number of rows, it is natural that we can combine them "horizontally".

In [170]:
pd.concat([df1, df2], axis = 1)

a  b  c  d  e
one    0  1  2  0  1
two    3  4  5  2  3
three  6  7  8  4  5

- The argument "axis = 1" means expanding along the column indices. Setting "axis = 0" will combine two data frames with same number of columns vertically. 

In [58]:
df1 = pd.DataFrame(np.arange(9).reshape(3,3))
df1.columns = ['a','b','c']
df1

a  b  c
0  0  1  2
1  3  4  5
2  6  7  8

In [60]:
df2 = pd.DataFrame(np.arange(15).reshape(5,3))
df2.columns = ['a','b','c']
df2

a   b   c
0   0   1   2
1   3   4   5
2   6   7   8
3   9  10  11
4  12  13  14

In [68]:
df = pd.concat([df1,df2], axis=0)
df.index = range(8)
df

a   b   c
0   0   1   2
1   3   4   5
2   6   7   8
3   0   1   2
4   3   4   5
5   6   7   8
6   9  10  11
7  12  13  14

**Exercise 6**

In the iPython notebook, let's create a data frame below. How should we combine it with the old Employee? Observe that this is a data frame with new features.

In [71]:
new_features = pd.DataFrame({'Title': ['analyst', 'associate', 'VP', 'analyst'],
                            'Education':['Bachelor','PHD','Master','Master'],
                           'Sex':['M','M','M','M']},
                            index=['Bob', 'Sam', 'Peter', 'Jake'])

In [72]:
new_features

Education Sex      Title
Bob    Bachelor   M    analyst
Sam         PHD   M  associate
Peter    Master   M         VP
Jake     Master   M    analyst

In [73]:
Employees.index = ['Bob','Sam','Peter','Jake']
Employees

Name  Year Department
Bob      Bob     1         IT
Sam      Sam     3      Trade
Peter  Peter     8         HR
Jake    Jake     2         IT

In [74]:
#### Your code here

# before concatenating horizontally, both data frames should have the same indexes

df = pd.concat([Employees, new_features], axis=1)
df

Name  Year Department Education Sex      Title
Bob      Bob     1         IT  Bachelor   M    analyst
Sam      Sam     3      Trade       PHD   M  associate
Peter  Peter     8         HR    Master   M         VP
Jake    Jake     2         IT    Master   M    analyst

<p><a name="merge"></a></p>
### merge
Merging is the most common way to combine multiple data frames. Let’s create two data frames first.

In [75]:
df1 = pd.DataFrame(np.array([0,0,0,2,2,2,8,8,8]).\
                   reshape((3, 3)),columns=['a','b','c'],
                   index=['one', 'two', 'three'])
df2 = pd.DataFrame(np.arange(6).reshape((3, 2)), 
                   columns=['b', 'd'],
                   index=['one', 'two', 'four'])

In [165]:
df1

a  b  c
one    0  0  0
two    2  2  2
three  8  8  8

In [166]:
df2

b  d
one   0  1
two   2  3
four  4  5

The code below identifies the column ‘b’ from both data frames. The argument 'inner' means it only keeps rows occur in both data frames.

In [172]:
pd.merge(df1, df2, how='inner', on ='b')

a  b  c  d
0  0  0  0  1
1  2  2  2  3

Without specifying 'how', it’s default to be 'inner'. So the following code performs the same task as above.

In [173]:
pd.merge(df1, df2, on ='b')

a  b  c  d
0  0  0  0  1
1  2  2  2  3

If we want to keep every row in df1, then we can specify how = "left".

In [174]:
pd.merge(df1, df2, how='left', on ='b')

a  b  c    d
0  0  0  0  1.0
1  2  2  2  3.0
2  8  8  8  NaN

If we want to keep all rows from both df1 and df2, then we can specify how = "outer".

In [175]:
pd.merge(df1, df2, how='outer', on ='b')

a    b    c    d
0  0.0  0.0  0.0  1.0
1  2.0  2.0  2.0  3.0
2  8.0  8.0  8.0  NaN
3  NaN  4.0  NaN  5.0

We can also merge on columns with different columns.

In [176]:
pd.merge(df1, df2, left_on='a', right_on='b')

a  b_x  c  b_y  d
0  0    0  0    0  1
1  2    2  2    2  3

**Exercise 7**

- Run the following code to create a data frame, 'Salary'. How is this related to the Employee data frame? Why do we separate this piece of information into another data frame?
- How should we combine the two data frames in a meaningful way?

In [ ]:
# Your code here

<p><a name="SF"></a></p>
### selection and filter

The `loc` method provides purely label (index/columns)-based indexing. This method only allows you do selection from a data frame by its index and columns. For example:

In [76]:
df1

a  b  c
one    0  0  0
two    2  2  2
three  8  8  8

In [178]:
df1['a']

one      0
two      2
three    8
Name: a, dtype: int32

In [179]:
df1.loc['two'] # the row that has index two

a    2
b    2
c    2
Name: two, dtype: int32

You can also pass a second parameter to loc to specify which column you want to choose. For example:

In [181]:
df1.loc['two', 'b'] # the row that has index two and column b

2

Fancy indexing as in Numpy can be done with `loc` in pandas as well. We may select a row with a condition:

In [182]:
df1.loc[df1.a==0,:]

a  b  c
one  0  0  0

We may select columns in a similar way:

In [183]:
df1.loc[:,df1.loc['one']==0]

a  b  c
one    0  0  0
two    2  2  2
three  8  8  8

Note: loc only accepts labels as input. If you try to use numbers, it will give you an error. For example:

In [184]:
df1.loc[1, 2]

TypeError: cannot do label indexing on <class 'pandas.indexes.base.Index'> with these indexers [1] of <type 'int'>

If you want to select data by number, you need the help of iloc. The iloc method provides a purely position based indexing.

In [185]:
# select as a matrix 
# row 2, col 3
df1.iloc[1, 2]

2

In [186]:
# first row, first two columns
# return a Series
row1 = df1.iloc[0, :2]
row1

a    0
b    0
Name: one, dtype: int32

<p><a name="grouping"></a></p>
---
# Grouping and Aggregation

Grouping and  aggregation is a critical component in data analysis. It is often referred to a process with one or more of the following steps involved:

- **Splitting** data into groups based on some features.
- **Applying** a function to each group independently.
- **Combining** the result into data structure.

### Grouping

Grouping is actually a very natural operation. Let's create a smaple data frame.

In [77]:
np.random.seed(10)
df = pd.DataFrame({'key1':['a','a','b','b','a'],
                   'key2':['one','two','one','two','one'],
                   'data1': np.random.randn(5),
                   'data2': np.random.randn(5)})

df

data1     data2 key1 key2
0  1.331587 -0.720086    a  one
1  0.715279  0.265512    a  two
2 -1.545400  0.108549    b  one
3 -0.008384  0.004291    b  two
4  0.621336 -0.174600    a  one

A natural question is: How many `a` do we have in `key1`? One way to answer this is to group the data frame by the value in `key1`. That is:

In [78]:
group = df.groupby('key1')

`group` is assigned the value returned by the `groupby` function, whose type is:

In [191]:
print type(group)

<class 'pandas.core.groupby.DataFrameGroupBy'>


Here we introduce an important feature of the object. A `DataFrameGroupBy` object is an `iterable`. That says we can iterate over the object:

In [192]:
for item in group:
    print item

('a',       data1     data2 key1 key2
0  1.331587 -0.720086    a  one
1  0.715279  0.265512    a  two
4  0.621336 -0.174600    a  one)
('b',       data1     data2 key1 key2
2 -1.545400  0.108549    b  one
3 -0.008384  0.004291    b  two)


With a careful inspection we see that each `item` we printed is a `tuple` with two components. In Python, there is an alternative way of iteration:

In [193]:
for key, values in group:
    print key
    print '-'*55
    print values
    print '\n'

a
-------------------------------------------------------
      data1     data2 key1 key2
0  1.331587 -0.720086    a  one
1  0.715279  0.265512    a  two
4  0.621336 -0.174600    a  one


b
-------------------------------------------------------
      data1     data2 key1 key2
2 -1.545400  0.108549    b  one
3 -0.008384  0.004291    b  two




In this way we can print and inspect a `DataFrameGroupBy` object. We also see how **splitting** is done.

**Applying** and **combining** are often done together with a single function. For example: 

In [194]:
group.size()

key1
a    3
b    2
dtype: int64

In [198]:
group.mean()

data1     data2
key1                    
a     0.889400 -0.209725
b    -0.776892  0.056420

### Aggregration

We may group the dataframe by multiple keys:

In [195]:
group2 = df.groupby(['key1', 'key2'])
group2.mean()

data1     data2
key1 key2                    
a    one   0.976461 -0.447343
     two   0.715279  0.265512
b    one  -1.545400  0.108549
     two  -0.008384  0.004291

We may apply multiple functions to each group with the method `agg`:

In [199]:
group2.agg(['count', 'sum', 'min', 'max', 'mean', 'std'])

data1                                                   data2  \
          count       sum       min       max      mean       std count   
key1 key2                                                                 
a    one      2  1.952922  0.621336  1.331587  0.976461  0.502223     2   
     two      1  0.715279  0.715279  0.715279  0.715279       NaN     1   
b    one      1 -1.545400 -1.545400 -1.545400 -1.545400       NaN     1   
     two      1 -0.008384 -0.008384 -0.008384 -0.008384       NaN     1   

                                                             
                sum       min       max      mean       std  
key1 key2                                                    
a    one  -0.894686 -0.720086 -0.174600 -0.447343  0.385716  
     two   0.265512  0.265512  0.265512  0.265512       NaN  
b    one   0.108549  0.108549  0.108549  0.108549       NaN  
     two   0.004291  0.004291  0.004291  0.004291       NaN

The column std misses three values because each of ['a', 'one'], ['b', 'one'] and ['b', 'two'] includes only one row in df.
We may apply different aggregating functions to different columns. This can be done with a dictionary.

In [200]:
colFun = {'data1': ['min', 'max'], 'data2': ['mean','std']}
group.agg(colFun)

data1               data2          
           min       max      mean       std
key1                                        
a     0.621336  1.331587 -0.209725  0.493737
b    -1.545400 -0.008384  0.056420  0.073721

# Quiz
In this quiz, we will use the csv file **Temp.csv**. 
- Read it into a data frame, call it `Temp`. (Import the packages you think you need).

In [79]:
#### Your code here

import numpy as np
import pandas as pd
Temp = pd.read_csv('Temp.csv')
Temp

City        State  Temperature
0         NYC     New York           67
1      Albany     New York           49
2     Buffalo     New York           38
3    Hartford  Connecticut           63
4  Bridgeport  Connecticut           58
5      Treton   New Jersey           72
6      Newark   New Jersey           68

- We learned that the temperature at New Haven, Connecticut is currently 58 degree fahrenheit. Add this information into the DataFrame.

In [82]:
#### Your code here
new_row = pd.DataFrame({'City':['New Haven'], 'State':['Connecticut'], 'Temperature':[58]}, index=[7])
Temp.append(new_row)
Temp
# we can also use concat but I used append because we are only adding 1 row here

City        State  Temperature
0         NYC     New York           67
1      Albany     New York           49
2     Buffalo     New York           38
3    Hartford  Connecticut           63
4  Bridgeport  Connecticut           58
5      Treton   New Jersey           72
6      Newark   New Jersey           68

- Replace the names of the states by their abbreviations. That is 
    - Connecticut --> CT
    - New Jersey  --> NJ
    - New York    --> NY
    
- Checkout the documentation [here](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.replace.html) to see how to use the `replace` function of pandas.

In [81]:
new_row

City        State  Temperature
7  New Haven  Connecticut           58

In [251]:
#### Your code here

Temp.replace('Connecticut', 'CT', inplace = True)
Temp.replace('New Jersey', 'NJ', inplace = True)
Temp.replace('New York', 'NY', inplace = True)

Temp

City State  Temperature
0         NYC    NY           67
1      Albany    NY           49
2     Buffalo    NY           38
3    Hartford    CT           63
4  Bridgeport    CT           58
5      Treton    NJ           72
6      Newark    NJ           68

- Select the rows in New York.

In [252]:
#### Your code here
Temp[Temp['State']=='NY']

City State  Temperature
0      NYC    NY           67
1   Albany    NY           49
2  Buffalo    NY           38

- What is the average of the temperature of cities in NY?

In [258]:
# without group by:

a=Temp[Temp['State']=='NY']
a.loc[:,'Temperature'].mean()


51.333333333333336

In [253]:
# using group by:

group = Temp.groupby('State')
colFun = {'Temperature': ['mean']}
group.agg(colFun)



Temperature
             mean
State            
CT      60.500000
NJ      70.000000
NY      51.333333

- Find the mean and the standard deviation of the temperature of each state.

In [241]:
#### Your code here
colFun = {'Temperature': ['mean','std']}
group.agg(colFun)

Temperature           
             mean        std
State                       
CT      59.666667   2.886751
NJ      70.000000   2.828427
NY      51.333333  14.640128

- We know the capital of each state: 
    - Connecticut --> Hartford
    - New Jersey  --> Treton
    - New York    --> Albany
    
    Create a data frame, `Capital`, with two columns: State and Capital, which should look like:
    
|| State| Capital|
| :-: |:---: | :---:|
| 0| CT  | Hartford|
| 1| NJ | Treton|
| 2| NY| Albany|

In [247]:
#### Your code here
Capital = pd.DataFrame({'State':['CT','NJ','NY'], 'Capital':['Hartford','Treton','Albany']} )
Capital

Capital State
0  Hartford    CT
1    Treton    NJ
2    Albany    NY

- Mutate a new boolean column, `Capital`, to `Temp`, which is `True` if the city in the row is the capital of the state, else `False`.
- **Hint**: use the `merge` function to combine those two data frames and then compare the Capital column with the City column to see whether they are equal to each other.

In [261]:
#### Your code here

Temp = pd.merge(Temp, Capital, how='inner', on ='State')
Temp

City State  Temperature   Capital
0         NYC    NY           67    Albany
1      Albany    NY           49    Albany
2     Buffalo    NY           38    Albany
3    Hartford    CT           63  Hartford
4  Bridgeport    CT           58  Hartford
5      Treton    NJ           72    Treton
6      Newark    NJ           68    Treton

In [266]:
Temp['is_Capital'] = (Temp['City'] == Temp['Capital'])
Temp

City State  Temperature   Capital is_Capital
0         NYC    NY           67    Albany      False
1      Albany    NY           49    Albany       True
2     Buffalo    NY           38    Albany      False
3    Hartford    CT           63  Hartford       True
4  Bridgeport    CT           58  Hartford      False
5      Treton    NJ           72    Treton       True
6      Newark    NJ           68    Treton      False